from datetime import datetime
from enum import Enum

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic.alias_generators import to_camel


class CategoryEnum(str, Enum):
    ABO_PLATEFORME_VIDEO = "ABO_PLATEFORME_VIDEO"
    ABONNEMENTS_MUSEE = "ABONNEMENTS_MUSEE"
    ABONNEMENTS_SPECTACLE = "ABONNEMENTS_SPECTACLE"
    ACHAT_LOCATION_INSTRUMENT = "ACHAT_LOCATION_INSTRUMENT"
    ARTS_VISUELS = "ARTS_VISUELS"
    AUTRES_MEDIAS = "AUTRES_MEDIAS"
    BIBLIOTHEQUE_MEDIATHEQUE = "BIBLIOTHEQUE_MEDIATHEQUE"
    CARTES_CINEMA = "CARTES_CINEMA"
    CD = "CD"
    CONCERTS_EN_LIGNE = "CONCERTS_EN_LIGNE"
    CONCERTS_EVENEMENTS = "CONCERTS_EVENEMENTS"
    CONCOURS = "CONCOURS"
    CONFERENCES = "CONFERENCES"
    DEPRECIEE = "DEPRECIEE"
    DVD_BLU_RAY = "DVD_BLU_RAY"
    ESCAPE_GAMES = "ESCAPE_GAMES"
    EVENEMENTS_CINEMA = "EVENEMENTS_CINEMA"
    EVENEMENTS_PATRIMOINE = "EVENEMENTS_PATRIMOINE"
    FESTIVALS = "FESTIVALS"
    FESTIVAL_DU_LIVRE = "FESTIVAL_DU_LIVRE"
    JEUX_EN_LIGNE = "JEUX_EN_LIGNE"
    JEUX_PHYSIQUES = "JEUX_PHYSIQUES"
    LIVRES_AUDIO_PHYSIQUES = "LIVRES_AUDIO_PHYSIQUES"
    LIVRES_NUMERIQUE_ET_AUDIO = "LIVRES_NUMERIQUE_ET_AUDIO"
    LIVRES_PAPIER = "LIVRES_PAPIER"
    LUDOTHEQUE = "LUDOTHEQUE"
    MATERIELS_CREATIFS = "MATERIELS_CREATIFS"
    MUSIQUE_EN_LIGNE = "MUSIQUE_EN_LIGNE"
    PARTITIONS_DE_MUSIQUE = "PARTITIONS_DE_MUSIQUE"
    PODCAST = "PODCAST"
    PRATIQUES_ET_ATELIERS_ARTISTIQUES = "PRATIQUES_ET_ATELIERS_ARTISTIQUES"
    PRATIQUE_ARTISTIQUE_EN_LIGNE = "PRATIQUE_ARTISTIQUE_EN_LIGNE"
    PRESSE_EN_LIGNE = "PRESSE_EN_LIGNE"
    RENCONTRES = "RENCONTRES"
    RENCONTRES_EN_LIGNE = "RENCONTRES_EN_LIGNE"
    RENCONTRES_EVENEMENTS = "RENCONTRES_EVENEMENTS"
    SALONS_ET_METIERS = "SALONS_ET_METIERS"
    SEANCES_DE_CINEMA = "SEANCES_DE_CINEMA"
    SPECTACLES_ENREGISTRES = "SPECTACLES_ENREGISTRES"
    SPECTACLES_REPRESENTATIONS = "SPECTACLES_REPRESENTATIONS"
    VIDEOS_ET_DOCUMENTAIRES = "VIDEOS_ET_DOCUMENTAIRES"
    VINYLES = "VINYLES"
    VISITES_CULTURELLES = "VISITES_CULTURELLES"
    VISITES_CULTURELLES_EN_LIGNE = "VISITES_CULTURELLES_EN_LIGNE"


class SubcategoryEnum(str, Enum):
    ABO_BIBLIOTHEQUE = "ABO_BIBLIOTHEQUE"
    ABO_CONCERT = "ABO_CONCERT"
    ABO_JEU_VIDEO = "ABO_JEU_VIDEO"
    ABO_LIVRE_NUMERIQUE = "ABO_LIVRE_NUMERIQUE"
    ABO_LUDOTHEQUE = "ABO_LUDOTHEQUE"
    ABO_MEDIATHEQUE = "ABO_MEDIATHEQUE"
    ABO_PLATEFORME_MUSIQUE = "ABO_PLATEFORME_MUSIQUE"
    ABO_PLATEFORME_VIDEO = "ABO_PLATEFORME_VIDEO"
    ABO_PRATIQUE_ART = "ABO_PRATIQUE_ART"
    ABO_PRESSE_EN_LIGNE = "ABO_PRESSE_EN_LIGNE"
    ABO_SPECTACLE = "ABO_SPECTACLE"
    ACHAT_INSTRUMENT = "ACHAT_INSTRUMENT"
    ACTIVATION_EVENT = "ACTIVATION_EVENT"
    ACTIVATION_THING = "ACTIVATION_THING"
    APP_CULTURELLE = "APP_CULTURELLE"
    ATELIER_PRATIQUE_ART = "ATELIER_PRATIQUE_ART"
    AUTRE_SUPPORT_NUMERIQUE = "AUTRE_SUPPORT_NUMERIQUE"
    BON_ACHAT_INSTRUMENT = "BON_ACHAT_INSTRUMENT"
    CAPTATION_MUSIQUE = "CAPTATION_MUSIQUE"
    CARTE_CINE_ILLIMITE = "CARTE_CINE_ILLIMITE"
    CARTE_CINE_MULTISEANCES = "CARTE_CINE_MULTISEANCES"
    CARTE_JEUNES = "CARTE_JEUNES"
    CARTE_MUSEE = "CARTE_MUSEE"
    CINE_PLEIN_AIR = "CINE_PLEIN_AIR"
    CINE_VENTE_DISTANCE = "CINE_VENTE_DISTANCE"
    CONCERT = "CONCERT"
    CONCOURS = "CONCOURS"
    CONFERENCE = "CONFERENCE"
    DECOUVERTE_METIERS = "DECOUVERTE_METIERS"
    ESCAPE_GAME = "ESCAPE_GAME"
    EVENEMENT_CINE = "EVENEMENT_CINE"
    EVENEMENT_JEU = "EVENEMENT_JEU"
    EVENEMENT_MUSIQUE = "EVENEMENT_MUSIQUE"
    EVENEMENT_PATRIMOINE = "EVENEMENT_PATRIMOINE"
    FESTIVAL_ART_VISUEL = "FESTIVAL_ART_VISUEL"
    FESTIVAL_CINE = "FESTIVAL_CINE"
    FESTIVAL_LIVRE = "FESTIVAL_LIVRE"
    FESTIVAL_MUSIQUE = "FESTIVAL_MUSIQUE"
    FESTIVAL_SPECTACLE = "FESTIVAL_SPECTACLE"
    JEU_EN_LIGNE = "JEU_EN_LIGNE"
    JEU_SUPPORT_PHYSIQUE = "JEU_SUPPORT_PHYSIQUE"
    LIVESTREAM_EVENEMENT = "LIVESTREAM_EVENEMENT"
    LIVESTREAM_MUSIQUE = "LIVESTREAM_MUSIQUE"
    LIVESTREAM_PRATIQUE_ARTISTIQUE = "LIVESTREAM_PRATIQUE_ARTISTIQUE"
    LIVRE_AUDIO_PHYSIQUE = "LIVRE_AUDIO_PHYSIQUE"
    LIVRE_NUMERIQUE = "LIVRE_NUMERIQUE"
    LIVRE_PAPIER = "LIVRE_PAPIER"
    LOCATION_INSTRUMENT = "LOCATION_INSTRUMENT"
    MATERIEL_ART_CREATIF = "MATERIEL_ART_CREATIF"
    MUSEE_VENTE_DISTANCE = "MUSEE_VENTE_DISTANCE"
    OEUVRE_ART = "OEUVRE_ART"
    PARTITION = "PARTITION"
    PLATEFORME_PRATIQUE_ARTISTIQUE = "PLATEFORME_PRATIQUE_ARTISTIQUE"
    PRATIQUE_ART_VENTE_DISTANCE = "PRATIQUE_ART_VENTE_DISTANCE"
    PODCAST = "PODCAST"
    RENCONTRE_EN_LIGNE = "RENCONTRE_EN_LIGNE"
    RENCONTRE_JEU = "RENCONTRE_JEU"
    RENCONTRE = "RENCONTRE"
    SALON = "SALON"
    SEANCE_CINE = "SEANCE_CINE"
    SEANCE_ESSAI_PRATIQUE_ART = "SEANCE_ESSAI_PRATIQUE_ART"
    SPECTACLE_ENREGISTRE = "SPECTACLE_ENREGISTRE"
    SPECTACLE_REPRESENTATION = "SPECTACLE_REPRESENTATION"
    SPECTACLE_VENTE_DISTANCE = "SPECTACLE_VENTE_DISTANCE"
    SUPPORT_PHYSIQUE_FILM = "SUPPORT_PHYSIQUE_FILM"
    SUPPORT_PHYSIQUE_MUSIQUE_CD = "SUPPORT_PHYSIQUE_MUSIQUE_CD"
    SUPPORT_PHYSIQUE_MUSIQUE_VINYLE = "SUPPORT_PHYSIQUE_MUSIQUE_VINYLE"
    TELECHARGEMENT_LIVRE_AUDIO = "TELECHARGEMENT_LIVRE_AUDIO"
    TELECHARGEMENT_MUSIQUE = "TELECHARGEMENT_MUSIQUE"
    VISITE_GUIDEE = "VISITE_GUIDEE"
    VISITE_VIRTUELLE = "VISITE_VIRTUELLE"
    VISITE = "VISITE"
    VOD = "VOD"


class SearchGroupNameEnum(str, Enum):
    ARTS_LOISIRS_CREATIFS = "ARTS_LOISIRS_CREATIFS"
    CARTES_JEUNES = "CARTES_JEUNES"
    CONCERTS_FESTIVALS = "CONCERTS_FESTIVALS"
    EVENEMENTS_EN_LIGNE = "EVENEMENTS_EN_LIGNE"
    CINEMA = "CINEMA"
    FILMS_DOCUMENTAIRES_SERIES = "FILMS_DOCUMENTAIRES_SERIES"
    JEUX_JEUX_VIDEOS = "JEUX_JEUX_VIDEOS"
    LIVRES = "LIVRES"
    MEDIA_PRESSE = "MEDIA_PRESSE"
    MUSEES_VISITES_CULTURELLES = "MUSEES_VISITES_CULTURELLES"
    MUSIQUE = "MUSIQUE"
    RENCONTRES_CONFERENCES = "RENCONTRES_CONFERENCES"
    SPECTACLES = "SPECTACLES"


class PlaylistRequestParams(BaseModel):
    """
    Strict validation schema for incoming HTTP POST payloads.

    This model acts as a gatekeeper, ensuring the frontend sends correctly
    formatted filters. It uses an alias generator to automatically convert
    incoming camelCase JSON (e.g., 'startDate') into Pythonic snake_case
    attributes ('start_date').
    """

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True, extra="forbid")

    # --- Temporal Constraints ---
    start_date: datetime | None = None
    end_date: datetime | None = None
    is_event: bool | None = None

    # --- Contextual & Format Constraints ---
    is_duo: bool | None = None
    is_restrained: bool | None = True
    is_digital: bool | None = None

    # --- Financial Constraints ---
    price_max: float | None = None
    price_min: float | None = None

    # --- Categorization Filters ---
    categories: list[CategoryEnum] | None = None
    subcategories: list[SubcategoryEnum] | None = None
    search_group_names: list[SearchGroupNameEnum] | None = None

    # --- Granular Classification (GTL) Filters ---
    gtl_ids: list[str] | None = None
    gtl_l1: list[str] | None = None
    gtl_l2: list[str] | None = None
    gtl_l3: list[str] | None = None
    gtl_l4: list[str] | None = None

    # --- Diversification & Orchestration Rules ---
    is_reco_shuffled: bool | None = None
    submixing_feature_dict: dict[str, str] | None = None


class RecommendationMetadata(BaseModel):
    """
    Metadata describing how the recommendation was generated.
    Useful for client-side analytics, A/B testing, and debugging.
    """

    reco_origin: str
    model_origin: str
    call_id: str


class RecommendationResponse(BaseModel):
    """
    The final standard payload returned to the client application.
    Contains the ordered list of offer IDs to display in the UI.
    """

    playlist_recommended_offers: list[str]
    params: RecommendationMetadata
