services:
  testdb:
    image: postgis/postgis:12-3.3
    container_name: testdb
    ports:
      - "${SQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - SQL_PORT=5439
      - DB_NAME=db
