name: API Reco Test Integration

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
      DATA_GCP_PROJECT:
         type: string
         required: true
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT:
        required: true

jobs:
  tests-integration-api-reco:
    name: "Tests Integration sur l'API RECO"
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: 'write'
      id-token: 'write'
    container: postman/newman
    defaults:
     run: 
       working-directory: "apps/recommendation/api/postman"
    steps:
      - uses: actions/checkout@v3
      - run: echo "running integration test on ${{ inputs.ENV }}"
      - id: openid-auth
        name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      - name: Get Secret
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
           secrets: API_RCO_TOKEN:${{ inputs.DATA_GCP_PROJECT }}/api-reco-token-${{ inputs.ENV }}
      - name: Run tests collection
        run: newman run api_integration_tests.postman_collection.json --environment ${{ inputs.ENV }}.postman_environment.json --env-var "api_token=${{ steps.secrets.outputs.API_RCO_TOKEN }}"
