name: "Deploy API Reco V2"

on:
  push:
    branches:
      - main
      - staging
      - production
    paths:
      - "apps/recommendation_v2/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - production
      no_traffic:
        description: "Deploy without routing traffic (useful to prepare A/B testing)"
        required: true
        default: true
        type: boolean

env:
  DOCKER_REGISTRY_PROJECT_ID: "passculture-infra-prod"
  DOCKER_REGISTRY_REGION: "europe-west1"
  DOCKER_REGISTRY_REPOSITORY: "pass-culture-artifact-registry"

jobs:
  setup-job:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-variable.outputs.env_name }}
      no_traffic: ${{ steps.set-variable.outputs.no_traffic }}
    steps:
      - name: "Set environment variable"
        id: "set-variable"
        env:
          REF: ${{ github.ref }}
          ENV: ${{ inputs.environment }}
          NO_TRAFFIC: ${{ inputs.no_traffic }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "env_name=$ENV" | tee -a "$GITHUB_OUTPUT"
            echo "no_traffic=$NO_TRAFFIC" | tee -a "$GITHUB_OUTPUT"
          elif [ "$REF" = "refs/heads/main" ]; then
            echo "env_name=dev" | tee -a "$GITHUB_OUTPUT"
            echo "no_traffic=true" | tee -a "$GITHUB_OUTPUT"
          elif [ "$REF" = "refs/heads/staging" ]; then
            echo "env_name=staging" | tee -a "$GITHUB_OUTPUT"
            echo "no_traffic=true" | tee -a "$GITHUB_OUTPUT"
          elif [ "$REF" = "refs/heads/production" ]; then
            echo "env_name=production" | tee -a "$GITHUB_OUTPUT"
            echo "no_traffic=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "env_name=dev" | tee -a "$GITHUB_OUTPUT"
            echo "no_traffic=true" | tee -a "$GITHUB_OUTPUT"
          fi

  build-and-push-docker-image:
    name: "Build image job"
    needs: [setup-job]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable_build_reco_image.yml
    with:
      app_path: apps/recommendation_v2
      image_name: recommendation_v2
      push_latest: true
      TARGET_ENV: ${{ needs.setup-job.outputs.env_name }}
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

  deploy-api:
    needs: [setup-job, build-and-push-docker-image]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable_deploy_reco_v2_cloudrun.yml
    with:
      image: "${{ needs.build-and-push-docker-image.outputs.docker_repo }}/api-data/recommendation_v2:${{ needs.build-and-push-docker-image.outputs.short_sha }}"
      suffix: "v2-${{ needs.build-and-push-docker-image.outputs.very_short_sha }}-${{ needs.build-and-push-docker-image.outputs.rand }}"
      tag: "reco-v2"
      no_traffic: ${{ needs.setup-job.outputs.no_traffic }}
      env_long_name: ${{ needs.build-and-push-docker-image.outputs.env_long_name }}
      secret_env_name: ${{ needs.build-and-push-docker-image.outputs.secret_env_name }}
      TARGET_ENV: ${{ needs.setup-job.outputs.env_name }}
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

  slack-notification:
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-job.outputs.env_name }}
    needs: [setup-job, deploy-api]

    permissions:
      id-token: write
    if: always()
    steps:
      - name: "Connect to Secret Manager"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get secrets for Slack"
        id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
      - uses: technote-space/workflow-conclusion-action@v3
      - name: "Post to a Slack channel"
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C01GVAXM02W" # alerts_data
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "${{ env.WORKFLOW_CONCLUSION == 'failure' && '#A30002' || '#36a64f' }}",
                  "author_name": "${{github.actor}}",
                  "author_link": "https://github.com/${{github.actor}}",
                  "author_icon": "https://github.com/${{github.actor}}.png",
                  "title": "API Reco V2 Deployment",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "Le déploiement de `l'API reco v2 sur ${{ needs.setup-job.outputs.env_name }}` est ${{ env.WORKFLOW_CONCLUSION == 'failure' && 'échoué :boom:' || 'réussi :muscle:' }}"
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }
